language: python

matrix:
  include:
  - python: "3.6"

install:
- sudo apt-get update
- python setup.py install
- pip install -r requirements_test.txt

script:
- py.test --cov taar_lite --cov-report term-missing tests
